disabled_rules:
- multiple_closures_with_trailing_closure
- empty_enum_arguments
- identifier_name
- inclusive_language
- empty_count

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

function_body_length:
    warning: 400
    error: 500

function_parameter_count:
    warning: 10
    error: 15

type_body_length:
    warning: 400
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
line_length:
    warning: 400
    error: 500
    
cyclomatic_complexity:
    warning: 25
    error: 50
    
reporter: "xcode"
